<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/button/button.html. Tokens and the item stylesheet apply
     unchanged; Svelte is the consumer's dependency. -->

<script>
  let { variant = "primary", disabled = false, children, ...rest } = $props();
</script>

<button class="uifa-button" data-uifa-variant={variant} disabled={disabled} {...rest}>
  {@render children?.()}
</button>
