<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/card/card.html. Tokens and the item stylesheet apply
     unchanged; Svelte is the consumer's dependency. -->

<script>
  let { title, body, actions, ...rest } = $props();
</script>

<article class="uifa-card" {...rest}>
  <h3 data-uifa-slot="title">{@render title?.()}</h3>
  <p data-uifa-slot="body">{@render body?.()}</p>
  <div data-uifa-slot="actions">{@render actions?.()}</div>
</article>
