<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/chip/chip.html. Tokens and the item stylesheet apply
     unchanged; Svelte is the consumer's dependency. -->

<script>
  let { variant = "neutral", children, ...rest } = $props();
</script>

<span class="uifa-chip" data-uifa-variant={variant} {...rest}>
  {@render children?.()}
</span>
