<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/form-field/form-field.html. Tokens and the item stylesheet apply
     unchanged; Svelte is the consumer's dependency. -->

<script>
  let { variant = "text", disabled = false, label, ...rest } = $props();
</script>

<label class="uifa-field">
  <span data-uifa-slot="label">{@render label?.()}</span>
  {#if variant === "textarea"}
    <textarea class="uifa-field-input" data-uifa-variant="textarea" rows={4} disabled={disabled} {...rest}></textarea>
  {:else}
    <input class="uifa-field-input" type="text" disabled={disabled} {...rest} />
  {/if}
</label>
