// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Fixture paths resolve from the kit root (npm run test-adapters cwd).
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "vitest";
import { render } from "@testing-library/react";
import { assertFixture } from "../../scripts/lib/fixture.mjs";
import { Badge } from "./badge.jsx";

describe("Badge adapter", () => {
  it("renders the accessible DOM items/badge promises", () => {
    render(
      <>
        <Badge>In review</Badge>
        {" "}
        <Badge variant="ok">Open</Badge>
        {" "}
        <Badge variant="warn">Due soon</Badge>
        {" "}
        <Badge variant="danger">Expired</Badge>
        {" "}
        <Badge variant="muted">Closed</Badge>
      </>
    );
    assertFixture(readFileSync(resolve("items/badge/fixture.aria.yml"), "utf8"));
  });
});
