// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Vanilla twin: items/badge/badge.html. Tokens and the item stylesheet apply
// unchanged; React is the consumer's dependency.

/**
 * Badge: Small status label: accent, ok, warn, danger, and muted outline variants.
 *
 * Children fill the default slot.
 *
 * @param {object} props
 * @param {import("react").ReactNode} [props.children] Default slot content.
 * @param {"accent"|"ok"|"warn"|"danger"|"muted"} [props.variant="accent"] Visual variant; the closed data-uifa-variant table.
 *
 * Rest props spread onto the root element.
 */
export function Badge({ variant = "accent", children, ...rest }) {
  return (
    <span className="uifa-badge" data-uifa-variant={variant} {...rest}>
      {children}
    </span>
  );
}
