// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Fixture paths resolve from the kit root (npm run test-adapters cwd).
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "vitest";
import { render } from "@testing-library/react";
import { assertFixture } from "../../scripts/lib/fixture.mjs";
import { Button } from "./button.jsx";

describe("Button adapter", () => {
  it("renders the accessible DOM items/button promises", () => {
    render(
      <>
        <Button>Save changes</Button>
        <Button variant="secondary">Preview</Button>
        <Button variant="danger">Delete project</Button>
        <Button variant="small">Compact action</Button>
        <Button disabled>Saved</Button>
      </>
    );
    assertFixture(readFileSync(resolve("items/button/fixture.aria.yml"), "utf8"));
  });
});
