// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Vanilla twin: items/button/button.html. Tokens and the item stylesheet apply
// unchanged; React is the consumer's dependency.

/**
 * Button: Primary, secondary, danger, and compact action buttons with disabled, hover, and focus states.
 *
 * Children fill the default slot.
 *
 * @param {object} props
 * @param {import("react").ReactNode} [props.children] Default slot content.
 * @param {"primary"|"secondary"|"danger"|"small"} [props.variant="primary"] Visual variant; the closed data-uifa-variant table.
 * @param {boolean} [props.disabled=false] Native disabled attribute; blocks interaction and dims via tokens.
 *
 * Rest props spread onto the root element.
 */
export function Button({ variant = "primary", disabled = false, children, ...rest }) {
  return (
    <button className="uifa-button" data-uifa-variant={variant} disabled={disabled} {...rest}>
      {children}
    </button>
  );
}
