// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Fixture paths resolve from the kit root (npm run test-adapters cwd).
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "vitest";
import { render } from "@testing-library/react";
import { assertFixture } from "../../scripts/lib/fixture.mjs";
import { Card } from "./card.jsx";

describe("Card adapter", () => {
  it("renders the accessible DOM items/card promises", () => {
    render(
      <>
        <Card
          title="Usage summary"
          body="Your workspace used 42% of its monthly quota. Upgrade any time; usage resets on the first of the month."
          actions={<button type="button">View usage</button>}
        />
      </>
    );
    assertFixture(readFileSync(resolve("items/card/fixture.aria.yml"), "utf8"));
  });
});
