// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Vanilla twin: items/card/card.html. Tokens and the item stylesheet apply
// unchanged; React is the consumer's dependency.

/**
 * Card: Flat surface card with one radius and theme-defined shadow character.
 *
 * @param {object} props
 * @param {import("react").ReactNode} [props.title] Card heading; renders in the h3.
 * @param {import("react").ReactNode} [props.body] Card copy; renders in the p.
 * @param {import("react").ReactNode} [props.actions] Action cluster; renders in the trailing div.
 *
 * Rest props spread onto the root element.
 */
export function Card({ title, body, actions, ...rest }) {
  return (
    <article className="uifa-card" {...rest}>
      <h3 data-uifa-slot="title">{title}</h3>
      <p data-uifa-slot="body">{body}</p>
      <div data-uifa-slot="actions">{actions}</div>
    </article>
  );
}
