// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Vanilla twin: items/chip/chip.html. Tokens and the item stylesheet apply
// unchanged; React is the consumer's dependency.

/**
 * Chip: Pill-radius tag for filters and metadata: neutral, accent, and warn variants.
 *
 * Children fill the default slot.
 *
 * @param {object} props
 * @param {import("react").ReactNode} [props.children] Default slot content.
 * @param {"neutral"|"accent"|"warn"} [props.variant="neutral"] Visual variant; the closed data-uifa-variant table.
 *
 * Rest props spread onto the root element.
 */
export function Chip({ variant = "neutral", children, ...rest }) {
  return (
    <span className="uifa-chip" data-uifa-variant={variant} {...rest}>
      {children}
    </span>
  );
}
