// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Fixture paths resolve from the kit root (npm run test-adapters cwd).
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "vitest";
import { render } from "@testing-library/react";
import { assertFixture } from "../../scripts/lib/fixture.mjs";
import { Chip } from "./chip.jsx";

describe("Chip adapter", () => {
  it("renders the accessible DOM items/chip promises", () => {
    render(
      <>
        <Chip>design</Chip>
        {" "}
        <Chip variant="accent">featured</Chip>
        {" "}
        <Chip variant="warn">needs review</Chip>
      </>
    );
    assertFixture(readFileSync(resolve("items/chip/fixture.aria.yml"), "utf8"));
  });
});
