// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Vanilla twin: items/form-field/form-field.html. Tokens and the item stylesheet apply
// unchanged; React is the consumer's dependency.

/**
 * Form field: Label, text input, and textarea with an accent focus ring.
 *
 * @param {object} props
 * @param {"text"|"textarea"} [props.variant="text"] Control to render: single-line input or multi-line textarea.
 * @param {boolean} [props.disabled=false] Disables the rendered control.
 * @param {import("react").ReactNode} [props.label] Visible label text bound to the control.
 *
 * Rest props spread onto the rendered control (name, placeholder, value, onChange, ...).
 */
export function FormField({ variant = "text", disabled = false, label, ...rest }) {
  return (
    <label className="uifa-field">
      <span data-uifa-slot="label">{label}</span>
      {variant === "textarea" ? (
        <textarea className="uifa-field-input" data-uifa-variant="textarea" rows={4} disabled={disabled} {...rest} />
      ) : (
        <input className="uifa-field-input" type="text" disabled={disabled} {...rest} />
      )}
    </label>
  );
}
