// GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit.
// Fixture paths resolve from the kit root (npm run test-adapters cwd).
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "vitest";
import { render } from "@testing-library/react";
import { assertFixture } from "../../scripts/lib/fixture.mjs";
import { FormField } from "./form-field.jsx";

describe("FormField adapter", () => {
  it("renders the accessible DOM items/form-field promises", () => {
    render(
      <>
        <FormField label="Project name" name="project" placeholder="Acme Inc" />
        <FormField label="Locked field" name="locked" placeholder="Unavailable while synced" disabled />
        <FormField variant="textarea" label="Description" name="description" placeholder="What is this project for?" />
      </>
    );
    assertFixture(readFileSync(resolve("items/form-field/fixture.aria.yml"), "utf8"));
  });
});
