// Example themes: six complete visual identities demonstrating the semantic-role
// coverage the kit's items consume - three refreshed sets (paper, graphite,
// citrus) and three new dialects (brutalist, terminal, glass) whose structural
// moves live in themes/dialects/<slug>.css. A theme is a complete visual
// identity as a token set; swap this file for your own themes module to
// restyle every item. Pinned fg/bg pairs are contrast-validated by
// scripts/build-arena.mjs (via scripts/lib/color.mjs) before the generated
// surfaces are written; sizes derive from --uifa-space and --uifa-text-base
// via calc().
//
// Token contract (per-theme CSS custom properties + color-scheme):
//   --uifa-bg, --uifa-surface, --uifa-surface-2, --uifa-border,
//   --uifa-border-strong, --uifa-text, --uifa-text-muted, --uifa-faint
//   --uifa-accent, --uifa-accent-soft, --uifa-accent-fg  (the accent slot)
//   --uifa-ok, --uifa-ok-soft, --uifa-ok-fg              (status: success)
//   --uifa-warn, --uifa-warn-soft, --uifa-warn-fg        (status: warning)
//   --uifa-danger, --uifa-danger-soft, --uifa-danger-fg  (status: destructive)
//   --uifa-scrim                                         (overlay backdrop)
//   --uifa-radius-control, --uifa-radius-surface, --uifa-radius-pill,
//   --uifa-border-width                                  (shape tiers)
//   --uifa-shadow-char                                   (depth)
//   --uifa-font-display, --uifa-font-body, --uifa-font-mono,
//   --uifa-text-base                                     (type)
//   --uifa-space                                         (density base unit)
//   --uifa-duration, --uifa-ease                         (motion)
//   --uifa-corner-shape, --uifa-noise                    (optional texture;
//     absent means the loader supplies the defaults: round, none)
//   color-scheme                                         (light/dark)
//
// Each theme may carry a `dialect` slot (a CSS string). It is loader-filled
// from themes/dialects/<slug>.css by convention, never hand-inlined here;
// the loader tolerates a missing or empty dialect directory.

export const themes = [
  {
    slug: "paper",
    name: "Paper",
    mood: "editorial",
    notes: "Warm paper, near-black ink, serif display. Quiet, layered, unhurried.",
    tokens: {
      "--uifa-bg": "oklch(98% 0.006 85)",
      "--uifa-surface": "oklch(99.5% 0.004 90)",
      "--uifa-surface-2": "oklch(96.5% 0.008 85)",
      "--uifa-border": "oklch(89% 0.012 85)",
      "--uifa-border-strong": "oklch(76% 0.018 80)",
      "--uifa-text": "oklch(25% 0.012 75)",
      "--uifa-text-muted": "oklch(45% 0.018 75)",
      "--uifa-faint": "oklch(80% 0.01 80)",
      "--uifa-accent": "oklch(50% 0.12 55)",
      "--uifa-accent-soft": "oklch(94% 0.03 60)",
      "--uifa-accent-fg": "oklch(98% 0.006 85)",
      "--uifa-ok": "oklch(48% 0.11 155)",
      "--uifa-ok-soft": "oklch(95% 0.03 155)",
      "--uifa-ok-fg": "oklch(98% 0.006 155)",
      "--uifa-warn": "oklch(46% 0.1 70)",
      "--uifa-warn-soft": "oklch(96% 0.035 85)",
      "--uifa-warn-fg": "oklch(98% 0.006 85)",
      "--uifa-danger": "oklch(52% 0.17 30)",
      "--uifa-danger-soft": "oklch(95% 0.03 30)",
      "--uifa-danger-fg": "oklch(98% 0.005 30)",
      "--uifa-scrim": "oklch(25% 0.012 75 / 0.45)",
      "--uifa-radius-control": "6px",
      "--uifa-radius-surface": "10px",
      "--uifa-radius-pill": "999px",
      "--uifa-border-width": "1px",
      "--uifa-shadow-char":
        "0 1px 1px oklch(25% 0.012 75 / 0.06), 0 2px 6px oklch(25% 0.012 75 / 0.05), 0 12px 32px oklch(50% 0.12 55 / 0.05)",
      "--uifa-font-display": "Georgia, 'Times New Roman', serif",
      "--uifa-font-body": "system-ui, sans-serif",
      "--uifa-font-mono": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-text-base": "16px",
      "--uifa-space": "8px",
      "--uifa-duration": "180ms",
      "--uifa-ease": "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      // faint warm grain, consumed by dead-states' background-image
      "--uifa-noise":
        'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'140\' height=\'140\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.8\' numOctaves=\'2\' stitchTiles=\'stitch\'/%3E%3CfeColorMatrix values=\'0 0 0 0 0.42 0 0 0 0 0.38 0 0 0 0 0.3 0 0 0 0.05 0\'/%3E%3C/filter%3E%3Crect width=\'140\' height=\'140\' filter=\'url(%23n)\'/%3E%3C/svg%3E")',
      "color-scheme": "light",
    },
  },
  {
    slug: "graphite",
    name: "Graphite",
    mood: "technical",
    notes: "Dark pro-tool charcoal, three stepped surfaces, electric lime. Dense, flat, fast.",
    tokens: {
      "--uifa-bg": "oklch(16% 0.006 260)",
      "--uifa-surface": "oklch(20% 0.007 260)",
      "--uifa-surface-2": "oklch(25% 0.008 260)",
      "--uifa-border": "oklch(88% 0.004 260 / 0.14)",
      "--uifa-border-strong": "oklch(88% 0.004 260 / 0.3)",
      "--uifa-text": "oklch(93% 0.003 260)",
      "--uifa-text-muted": "oklch(70% 0.006 260)",
      "--uifa-faint": "oklch(40% 0.006 260)",
      "--uifa-accent": "oklch(82% 0.12 118)",
      "--uifa-accent-soft": "oklch(82% 0.12 118 / 0.16)",
      "--uifa-accent-fg": "oklch(17% 0.02 118)",
      "--uifa-ok": "oklch(75% 0.13 155)",
      "--uifa-ok-soft": "oklch(75% 0.13 155 / 0.16)",
      "--uifa-ok-fg": "oklch(16% 0.02 155)",
      "--uifa-warn": "oklch(79% 0.13 85)",
      "--uifa-warn-soft": "oklch(79% 0.13 85 / 0.16)",
      "--uifa-warn-fg": "oklch(17% 0.02 85)",
      "--uifa-danger": "oklch(68% 0.17 25)",
      "--uifa-danger-soft": "oklch(68% 0.17 25 / 0.16)",
      "--uifa-danger-fg": "oklch(16% 0.02 25)",
      "--uifa-scrim": "oklch(8% 0.005 260 / 0.65)",
      "--uifa-radius-control": "4px",
      "--uifa-radius-surface": "8px",
      "--uifa-radius-pill": "999px",
      "--uifa-border-width": "1px",
      "--uifa-shadow-char": "0 1px 2px oklch(0% 0 0 / 0.35)",
      "--uifa-font-display": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-font-body": "system-ui, sans-serif",
      "--uifa-font-mono": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-text-base": "15px",
      "--uifa-space": "8px",
      "--uifa-duration": "120ms",
      "--uifa-ease": "cubic-bezier(0, 0, 0.2, 1)",
      "color-scheme": "dark",
    },
  },
  {
    slug: "citrus",
    name: "Citrus",
    mood: "playful",
    notes: "Vivid orange accent, high-contrast ink, pill radius, hard sticker shadows.",
    tokens: {
      "--uifa-bg": "oklch(96.5% 0.025 100)",
      "--uifa-surface": "oklch(99% 0.012 105)",
      "--uifa-surface-2": "oklch(94% 0.035 100)",
      "--uifa-border": "oklch(86% 0.035 95)",
      "--uifa-border-strong": "oklch(70% 0.06 90)",
      "--uifa-text": "oklch(21% 0.015 110)",
      "--uifa-text-muted": "oklch(43% 0.02 110)",
      "--uifa-faint": "oklch(78% 0.03 100)",
      "--uifa-accent": "oklch(60% 0.18 55)",
      "--uifa-accent-soft": "oklch(93% 0.055 65)",
      "--uifa-accent-fg": "oklch(22% 0.02 100)",
      "--uifa-ok": "oklch(50% 0.13 150)",
      "--uifa-ok-soft": "oklch(93% 0.045 150)",
      "--uifa-ok-fg": "oklch(98% 0.01 150)",
      "--uifa-warn": "oklch(52% 0.12 75)",
      "--uifa-warn-soft": "oklch(94% 0.05 85)",
      "--uifa-warn-fg": "oklch(98% 0.01 85)",
      "--uifa-danger": "oklch(54% 0.2 28)",
      "--uifa-danger-soft": "oklch(93% 0.04 28)",
      "--uifa-danger-fg": "oklch(98% 0.01 28)",
      "--uifa-scrim": "oklch(21% 0.015 110 / 0.45)",
      "--uifa-radius-control": "16px",
      "--uifa-radius-surface": "20px",
      "--uifa-radius-pill": "999px",
      "--uifa-border-width": "1px",
      "--uifa-shadow-char":
        "0 2px 0 oklch(21% 0.015 110), 0 12px 28px oklch(60% 0.18 55 / 0.14)",
      "--uifa-font-display": "system-ui, sans-serif",
      "--uifa-font-body": "system-ui, sans-serif",
      "--uifa-font-mono": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-text-base": "16px",
      "--uifa-space": "8px",
      "--uifa-duration": "160ms",
      "--uifa-ease": "cubic-bezier(0.34, 1.4, 0.64, 1)",
      "color-scheme": "light",
    },
  },
  {
    slug: "brutalist",
    name: "Brutalist",
    mood: "raw",
    notes: "Thick near-black borders, one hard offset shadow, flat loud fills. The shadow disappears when you click.",
    tokens: {
      "--uifa-bg": "oklch(95% 0.012 95)",
      "--uifa-surface": "oklch(99% 0.005 100)",
      "--uifa-surface-2": "oklch(91% 0.02 95)",
      "--uifa-border": "oklch(22% 0.01 95)",
      "--uifa-border-strong": "oklch(14% 0.01 95)",
      "--uifa-text": "oklch(18% 0.01 95)",
      "--uifa-text-muted": "oklch(36% 0.012 95)",
      "--uifa-faint": "oklch(56% 0.012 95)",
      "--uifa-accent": "oklch(56% 0.21 257)",
      "--uifa-accent-soft": "oklch(90% 0.06 257)",
      "--uifa-accent-fg": "oklch(98% 0.005 257)",
      "--uifa-ok": "oklch(50% 0.16 148)",
      "--uifa-ok-soft": "oklch(93% 0.06 148)",
      "--uifa-ok-fg": "oklch(98% 0.01 148)",
      "--uifa-warn": "oklch(55% 0.13 82)",
      "--uifa-warn-soft": "oklch(95% 0.055 95)",
      "--uifa-warn-fg": "oklch(18% 0.01 95)",
      "--uifa-danger": "oklch(52% 0.2 27)",
      "--uifa-danger-soft": "oklch(94% 0.045 27)",
      "--uifa-danger-fg": "oklch(98% 0.01 27)",
      "--uifa-scrim": "oklch(14% 0.01 95 / 0.5)",
      "--uifa-radius-control": "4px",
      "--uifa-radius-surface": "4px",
      "--uifa-radius-pill": "8px",
      "--uifa-border-width": "2px",
      "--uifa-shadow-char": "4px 4px 0 0 oklch(14% 0.01 95)",
      "--uifa-font-display": "system-ui, sans-serif",
      "--uifa-font-body": "system-ui, sans-serif",
      "--uifa-font-mono": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-text-base": "16px",
      "--uifa-space": "8px",
      "--uifa-duration": "80ms",
      "--uifa-ease": "linear",
      "color-scheme": "light",
    },
  },
  {
    slug: "terminal",
    name: "Terminal",
    mood: "phosphor",
    notes: "Near-black CRT green: mono everything, hairline phosphor rules, scanlines and glow.",
    tokens: {
      "--uifa-bg": "oklch(12% 0.012 160)",
      "--uifa-surface": "oklch(15% 0.015 160)",
      "--uifa-surface-2": "oklch(18% 0.018 160)",
      "--uifa-border": "oklch(87% 0.17 150 / 0.28)",
      "--uifa-border-strong": "oklch(87% 0.17 150 / 0.55)",
      "--uifa-text": "oklch(87% 0.17 150)",
      "--uifa-text-muted": "oklch(70% 0.12 150)",
      "--uifa-faint": "oklch(45% 0.08 150)",
      "--uifa-accent": "oklch(87% 0.17 150)",
      "--uifa-accent-soft": "oklch(87% 0.17 150 / 0.14)",
      "--uifa-accent-fg": "oklch(13% 0.02 150)",
      "--uifa-ok": "oklch(80% 0.15 150)",
      "--uifa-ok-soft": "oklch(80% 0.15 150 / 0.14)",
      "--uifa-ok-fg": "oklch(13% 0.02 150)",
      "--uifa-warn": "oklch(80% 0.14 85)",
      "--uifa-warn-soft": "oklch(80% 0.14 85 / 0.14)",
      "--uifa-warn-fg": "oklch(14% 0.02 85)",
      "--uifa-danger": "oklch(70% 0.17 25)",
      "--uifa-danger-soft": "oklch(70% 0.17 25 / 0.14)",
      "--uifa-danger-fg": "oklch(13% 0.02 25)",
      "--uifa-scrim": "oklch(6% 0.01 160 / 0.7)",
      "--uifa-radius-control": "2px",
      "--uifa-radius-surface": "2px",
      "--uifa-radius-pill": "4px",
      "--uifa-border-width": "1px",
      "--uifa-shadow-char": "0 0 24px oklch(87% 0.17 150 / 0.08)",
      "--uifa-font-display": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-font-body": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-font-mono": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-text-base": "16px",
      "--uifa-space": "8px",
      "--uifa-duration": "120ms",
      "--uifa-ease": "linear",
      "color-scheme": "dark",
    },
  },
  {
    slug: "glass",
    name: "Glass",
    mood: "luminous",
    notes: "Dark glassmorphism: frosted translucent panels, edge light, slow fades over deep color.",
    tokens: {
      "--uifa-bg": "oklch(19% 0.035 275)",
      "--uifa-surface": "oklch(100% 0 0 / 0.07)",
      "--uifa-surface-2": "oklch(100% 0 0 / 0.13)",
      "--uifa-border": "oklch(100% 0 0 / 0.14)",
      "--uifa-border-strong": "oklch(100% 0 0 / 0.32)",
      "--uifa-text": "oklch(97% 0.004 275)",
      "--uifa-text-muted": "oklch(88% 0.006 275)",
      "--uifa-faint": "oklch(64% 0.015 275)",
      "--uifa-accent": "oklch(80% 0.14 305)",
      "--uifa-accent-soft": "oklch(100% 0 0 / 0.12)",
      "--uifa-accent-fg": "oklch(22% 0.05 305)",
      "--uifa-ok": "oklch(82% 0.13 150)",
      "--uifa-ok-soft": "oklch(82% 0.13 150 / 0.16)",
      "--uifa-ok-fg": "oklch(17% 0.03 150)",
      "--uifa-warn": "oklch(83% 0.12 85)",
      "--uifa-warn-soft": "oklch(83% 0.12 85 / 0.16)",
      "--uifa-warn-fg": "oklch(18% 0.03 85)",
      "--uifa-danger": "oklch(74% 0.15 25)",
      "--uifa-danger-soft": "oklch(74% 0.15 25 / 0.16)",
      "--uifa-danger-fg": "oklch(16% 0.03 25)",
      "--uifa-scrim": "oklch(12% 0.03 275 / 0.55)",
      "--uifa-radius-control": "16px",
      "--uifa-radius-surface": "24px",
      "--uifa-radius-pill": "999px",
      "--uifa-border-width": "1px",
      "--uifa-shadow-char": "0 8px 32px oklch(10% 0.03 275 / 0.4)",
      "--uifa-font-display": "system-ui, sans-serif",
      "--uifa-font-body": "system-ui, sans-serif",
      "--uifa-font-mono": "ui-monospace, Menlo, Consolas, monospace",
      "--uifa-text-base": "16px",
      "--uifa-space": "8px",
      "--uifa-duration": "250ms",
      "--uifa-ease": "cubic-bezier(0.4, 0, 0.2, 1)",
      "color-scheme": "dark",
    },
  },
];
