// Generates the arena: a self-contained catalog page rendering the sample UI
// and every item example across the example directions, plus themes/tokens.css
// (the direction token sets as plain CSS for standalone examples).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadKit } from "./lib/items.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const { directions, items } = await loadKit();

// themes/tokens.css: the base scale as CSS, keyed by [data-theme].
const tokensCss = [
  "/* GENERATED by scripts/build-arena.mjs from themes/directions.mjs - do not edit. */",
  ...directions.map((direction, index) => {
    const selector = index === 0 ? [":root", `[data-theme="${direction.slug}"]`] : [`[data-theme="${direction.slug}"]`];
    const body = Object.entries(direction.tokens)
      .map(([token, value]) => (token === "color-scheme" ? `  ${token}: ${value};` : `  ${token}: ${value};`))
      .join("\n");
    return `${selector.join(",\n")} {\n${body}\n}`;
  }),
].join("\n\n") + "\n";
writeFileSync(join(ROOT, "themes", "tokens.css"), tokensCss);

// Collect each item's example markup and scripts.
const itemBlocks = items.map((item) => {
  const css = item.manifest.files
    .filter((f) => f.type === "kit:style")
    .map((f) => readFileSync(join(item.dir, f.path), "utf8").trim())
    .join("\n\n");
  const behaviorFiles = new Map(
    item.manifest.files
      .filter((f) => f.type === "kit:behavior")
      .map((f) => [f.path, readFileSync(join(item.dir, f.path), "utf8").trim()])
  );
  const examplePath = item.manifest.files.find((f) => f.type === "kit:example").path;
  const example = readFileSync(join(item.dir, examplePath), "utf8");
  const bodyMatch = example.match(/<body[^>]*>([\s\S]*)<\/body>/);
  if (!bodyMatch) throw new Error(`items/${item.name}: example has no <body> to extract`);
  const body = bodyMatch[1].replace(/<script src="([^"]+)"><\/script>/g, (tag, src) => {
    const content = behaviorFiles.get(src);
    if (content === undefined) {
      throw new Error(`items/${item.name}: example references "${src}" which is not a declared kit:behavior file`);
    }
    return `<script>\n${content}\n</script>`;
  });
  return { name: item.name, css, body };
});

// Sample UI: one composed screen proving the items work together per direction.
const sampleUi = `
<header class="uif-top-nav">
  <a data-slot="wordmark" href="#">Acme</a>
  <nav data-slot="links" aria-label="Sample">
    <a href="#" aria-current="page">Overview</a>
    <a href="#">Projects</a>
    <a href="#">Settings</a>
  </nav>
  <div data-slot="actions"><a href="#">Sign out</a></div>
</header>
<div class="arena-sample">
  <form class="uif-filter-bar" role="search" aria-label="Sample filter">
    <input data-slot="search" type="search" placeholder="Search projects" aria-label="Search projects">
    <div data-slot="chips">
      <button type="button" data-slot="chip" aria-pressed="true">Active</button>
      <button type="button" data-slot="chip" aria-pressed="false">Archived</button>
      <button type="button" data-slot="chip" data-variant="warn" aria-pressed="false">Overdue</button>
    </div>
  </form>
  <div class="arena-columns">
    <article class="uif-card">
      <h3 data-slot="title">New project</h3>
      <p data-slot="body">Projects group episodes, assets, and delivery checks in one place.</p>
      <label class="uif-field">
        <span data-slot="label">Project name</span>
        <input class="uif-field-input" type="text" placeholder="Acme Inc">
      </label>
      <div data-slot="actions">
        <button class="uif-button" data-variant="primary">Create project</button>
        <button class="uif-button" data-variant="secondary">Cancel</button>
      </div>
    </article>
    <article class="uif-card">
      <h3 data-slot="title">Delivery queue</h3>
      <div data-slot="body" class="arena-rows">
        <div class="uif-link-row">
          <a data-slot="title" href="#">Episode 12: Designing for agents</a>
          <span data-slot="url">acme.example/12</span>
          <div data-slot="chips"><span data-slot="chip">podcast</span></div>
          <div data-slot="actions"><a href="#">Open</a></div>
        </div>
        <div class="uif-link-row">
          <a data-slot="title" href="#">Season wrap report</a>
          <span data-slot="url">acme.example/wrap</span>
          <div data-slot="chips"><span data-slot="chip">report</span></div>
          <div data-slot="actions"><a href="#">Open</a></div>
        </div>
        <p class="arena-badges"><span class="uif-badge" data-variant="ok">Open</span> <span class="uif-badge" data-variant="warn">Due soon</span> <span class="uif-badge" data-variant="muted">Closed</span></p>
      </div>
    </article>
    <article class="uif-card">
      <h3 data-slot="title">Playback</h3>
      <div data-slot="body" class="arena-stack">
        <div class="uif-player">
          <button type="button" data-slot="play" aria-label="Play">▶</button>
          <div data-slot="meta">
            <span data-slot="title">Episode 12: Designing for agents</span>
            <span data-slot="time">12:04 / 35:00</span>
          </div>
          <div data-slot="progress" role="progressbar" aria-label="Playback position" aria-valuemin="0" aria-valuemax="100" aria-valuenow="35">
            <span data-slot="progress-fill" style="width: 35%"></span>
          </div>
        </div>
        <div class="uif-segmented" role="radiogroup" aria-label="Sample range">
          <label class="uif-segmented-option"><input type="radio" name="sample-range" value="day" checked><span data-slot="segment">Day</span></label>
          <label class="uif-segmented-option"><input type="radio" name="sample-range" value="week"><span data-slot="segment">Week</span></label>
        </div>
        <label class="uif-toggle">
          <input class="uif-toggle-input" type="checkbox" role="switch" checked>
          <span data-slot="label">Autoplay next episode</span>
        </label>
        <button type="button" class="uif-modal-trigger" data-slot="sample-modal-open">Delete workspace</button>
      </div>
    </article>
  </div>
  <table class="uif-table" data-sortable>
    <thead>
      <tr>
        <th><input data-slot="select" type="checkbox" aria-label="Select all rows"></th>
        <th aria-sort="ascending"><button type="button">Name</button></th>
        <th>Status</th>
        <th><button type="button">Updated</button></th>
      </tr>
    </thead>
    <tbody>
      <tr><td><input data-slot="select" type="checkbox" aria-label="Select Atlas"></td><td>Atlas</td><td><span data-slot="status">Active</span></td><td>2026-09-21</td></tr>
      <tr><td><input data-slot="select" type="checkbox" aria-label="Select Beacon"></td><td>Beacon</td><td><span data-slot="status" data-variant="warn">Due soon</span></td><td>2026-09-24</td></tr>
      <tr><td><input data-slot="select" type="checkbox" aria-label="Select Compass"></td><td>Compass</td><td><span data-slot="status" data-variant="danger">Expired</span></td><td>2026-09-12</td></tr>
    </tbody>
  </table>
  <button type="button" class="uif-toast-trigger" data-slot="sample-toast-open">Show toast</button>
  <p class="arena-status-label">Status roles: ok, warn, danger, scrim</p>
  <div class="arena-scrim-demo">Content under the scrim</div>
</div>
<div class="uif-toast-region">
  <div class="uif-toast" data-variant="info" data-state="visible" role="status">
    <span data-slot="message">Sample workspace ready</span>
    <button type="button" data-slot="close">Dismiss</button>
  </div>
  <div class="uif-toast" data-variant="ok" data-state="visible" role="status">
    <span data-slot="message">Delivery queued</span>
    <button type="button" data-slot="close">Dismiss</button>
  </div>
  <div class="uif-toast" data-variant="warn" data-state="visible" role="status">
    <span data-slot="message">Storage almost full</span>
    <button type="button" data-slot="close">Dismiss</button>
  </div>
  <div class="uif-toast" data-variant="danger" data-state="visible" role="status">
    <span data-slot="message">Connection lost</span>
    <button type="button" data-slot="close">Dismiss</button>
  </div>
</div>
`.trim();

const iframeChrome = `
  *, *::before, *::after { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--bg);
    color: var(--text);
    font-family: var(--font-body);
    font-size: var(--text-base);
  }
  .arena-sample {
    padding: calc(var(--space) * 4);
    display: grid;
    gap: calc(var(--space) * 4);
  }
  .arena-columns {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: calc(var(--space) * 4);
  }
  .arena-stack { display: grid; gap: calc(var(--space) * 3); justify-items: start; }
  .arena-rows { display: grid; gap: calc(var(--space) * 1); }
  .arena-badges { margin: calc(var(--space) * 1) 0 0; display: flex; gap: calc(var(--space) * 2); flex-wrap: wrap; }
  .arena-status-label { margin: 0; font-family: var(--font-display); color: var(--text-muted); }
  .arena-scrim-demo {
    position: relative;
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: calc(var(--space) * 2);
    min-height: calc(var(--space) * 10);
    display: grid;
    place-items: center;
    color: var(--text-muted);
  }
  .arena-scrim-demo::after {
    content: "";
    position: absolute;
    inset: 0;
    background: var(--scrim);
    border-radius: inherit;
  }
  /* The catalog renders in flow: fixed regions would paint over the last item. */
  .uif-toast-region { position: static; justify-items: start; }
  .arena-sample .uif-toast-trigger { justify-self: start; }
  .arena-item {
    border-top: 1px solid var(--border);
    padding: calc(var(--space) * 4);
    display: grid;
    gap: calc(var(--space) * 3);
    justify-items: start;
  }
  .arena-item h3 {
    margin: 0;
    font-family: var(--font-display);
    font-size: calc(var(--text-base) * 0.875);
    font-weight: 600;
    color: var(--text-muted);
  }
`;

function directionDocument(direction) {
  const itemsHtml = itemBlocks
    .map(({ name, body }) => `<section class="arena-item"><h3>${name}</h3>\n${body}\n</section>`)
    .join("\n");
  return `<!doctype html>
<html lang="en" data-theme="${direction.slug}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
${directions.map((d, i) => {
  const selector = i === 0 ? [":root", `[data-theme="${d.slug}"]`] : [`[data-theme="${d.slug}"]`];
  const body = Object.entries(d.tokens).map(([t, v]) => `  ${t}: ${v};`).join("\n");
  return `${selector.join(",\n")} {\n${body}\n}`;
}).join("\n")}
</style>
<style>${itemBlocks.map((b) => b.css).join("\n\n")}</style>
<style>${iframeChrome}</style>
</head>
<body>
${sampleUi}
${itemsHtml}
</body>
</html>`;
}

const pages = directions.map((direction) => ({
  slug: direction.slug,
  name: direction.name,
  mood: direction.mood,
  notes: direction.notes,
  html: directionDocument(direction),
}));

const payload = JSON.stringify({ pages }).replace(/<\//g, "<\\/");

const arena = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>uiforagents arena</title>
<style>
  body { margin: 0; padding: 24px; font-family: system-ui, sans-serif; background: #eceae6; color: #26221e; }
  header { max-width: 1100px; margin: 0 auto 16px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  p { margin: 0; color: #6b645c; font-size: 13px; }
  main { max-width: 1100px; margin: 0 auto; display: grid; gap: 24px; }
  section h2 { font-size: 15px; margin: 0 0 8px; }
  iframe { width: 100%; border: 1px solid #d4d0c9; border-radius: 8px; background: #fff; }
</style>
</head>
<body>
<header>
  <h1>uiforagents arena</h1>
  <p>Every item and the sample UI, rendered across the example directions via tokens only. Generated by scripts/build-arena.mjs.</p>
</header>
<main id="frames"></main>
<script type="application/json" id="arena-payload">${payload}</script>
<script>
  const payload = JSON.parse(document.getElementById("arena-payload").textContent);
  const main = document.getElementById("frames");
  for (const page of payload.pages) {
    const section = document.createElement("section");
    const h2 = document.createElement("h2");
    h2.textContent = page.name + " · " + page.slug + " · " + page.mood;
    const frame = document.createElement("iframe");
    frame.title = page.name + " direction";
    frame.addEventListener("load", () => {
      try { frame.style.height = frame.contentDocument.documentElement.scrollHeight + "px"; } catch (err) {}
    });
    frame.srcdoc = page.html;
    section.append(h2, frame);
    main.append(section);
  }
</script>
</body>
</html>
`;
mkdirSync(join(ROOT, "docs"), { recursive: true });
writeFileSync(join(ROOT, "docs", "arena.html"), arena);

console.log(`build-arena: docs/arena.html and themes/tokens.css generated (${directions.length} directions, ${items.length} items)`);
