// Generates the arena: a self-contained catalog page rendering the sample UI
// and every item example across the example themes, plus themes/tokens.css
// (the theme token sets, cascade-layered, for standalone examples). Enforces
// the pinned fg/bg contrast pairs via scripts/lib/color.mjs before writing;
// all theme CSS is serialized through the shared scripts/lib/themes-css.mjs.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadKit, readText } from "./lib/items.mjs";
import { tokenPairRatio } from "./lib/color.mjs";
import { themesCss, themesLayerStyle } from "./lib/themes-css.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const { themes, items } = await loadKit();
const { version } = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));

// Pinned fg/bg pairs: text pairs at 4.5:1, foreground-on-accent and
// status/accent-on-soft pairs at the 3.0:1 WCAG large-text/UI threshold.
const CONTRAST_PAIRS = [
  { min: 4.5, pairs: [
    ["--uifa-text", "--uifa-bg"],
    ["--uifa-text", "--uifa-surface"],
    ["--uifa-text", "--uifa-surface-2"],
    ["--uifa-text-muted", "--uifa-bg"],
    ["--uifa-text-muted", "--uifa-surface"],
  ] },
  { min: 3, pairs: [
    ["--uifa-accent-fg", "--uifa-accent"],
    ["--uifa-ok-fg", "--uifa-ok"],
    ["--uifa-warn-fg", "--uifa-warn"],
    ["--uifa-danger-fg", "--uifa-danger"],
    ["--uifa-accent", "--uifa-bg"],
    ["--uifa-accent", "--uifa-surface"],
    ["--uifa-accent", "--uifa-accent-soft"],
    ["--uifa-ok", "--uifa-ok-soft"],
    ["--uifa-warn", "--uifa-warn-soft"],
    ["--uifa-danger", "--uifa-danger-soft"],
  ] },
];

const contrastFailures = [];
for (const theme of themes) {
  for (const { min, pairs } of CONTRAST_PAIRS) {
    for (const [fg, bg] of pairs) {
      const ratio = tokenPairRatio(theme.tokens, fg, bg);
      if (ratio < min) contrastFailures.push(`${theme.slug}: ${fg} on ${bg} is ${ratio.toFixed(2)}:1 (minimum ${min}:1)`);
    }
  }
}
if (contrastFailures.length > 0) {
  console.error(`build-arena: contrast validation failed\n${contrastFailures.join("\n")}`);
  process.exit(1);
}

// themes/tokens.css: the theme contract as cascade-layered CSS, keyed by
// [data-theme]; the first theme also owns :root.
const tokensCss = themesCss({
  themes,
  header: `/* GENERATED by scripts/build-arena.mjs from themes/index.mjs - uiforagents ${version} - do not edit. */`,
});
writeFileSync(join(ROOT, "themes", "tokens.css"), tokensCss);

// Collect each item's example markup and scripts.
const itemBlocks = items.map((item) => {
  const css = item.manifest.files
    .filter((f) => f.type === "kit:style")
    .map((f) => readText(join(item.dir, f.path)).trim())
    .join("\n\n");
  const behaviorFiles = new Map(
    item.manifest.files
      .filter((f) => f.type === "kit:behavior")
      .map((f) => [f.path, readText(join(item.dir, f.path)).trim()])
  );
  const examplePath = item.manifest.files.find((f) => f.type === "kit:example").path;
  const example = readText(join(item.dir, examplePath));
  const bodyMatch = example.match(/<body[^>]*>([\s\S]*)<\/body>/);
  if (!bodyMatch) throw new Error(`items/${item.name}: example has no <body> to extract`);
  const body = bodyMatch[1].replace(/<script src="([^"]+)"><\/script>/g, (tag, src) => {
    const content = behaviorFiles.get(src);
    if (content === undefined) {
      throw new Error(`items/${item.name}: example references "${src}" which is not a declared kit:behavior file`);
    }
    return `<script>\n${content}\n</script>`;
  });
  return { name: item.name, css, body };
});

// Sample UI: one composed screen proving the items work together per theme.
const sampleUi = `
<header class="uifa-top-nav">
  <a data-uifa-slot="wordmark" href="#">Acme</a>
  <nav data-uifa-slot="links" aria-label="Sample">
    <a href="#" aria-current="page">Overview</a>
    <a href="#">Projects</a>
    <a href="#">Settings</a>
  </nav>
  <div data-uifa-slot="actions"><a href="#">Sign out</a></div>
</header>
<div class="arena-sample">
  <div class="arena-page-head">
    <h2>Season overview</h2>
    <p>Plan, record, and ship every episode from one workspace.</p>
  </div>
  <form class="uifa-filter-bar" role="search" aria-label="Sample filter">
    <input data-uifa-slot="search" type="search" placeholder="Search projects" aria-label="Search projects">
    <div data-uifa-slot="chips">
      <button type="button" data-uifa-slot="chip" aria-pressed="true">Active</button>
      <button type="button" data-uifa-slot="chip" aria-pressed="false">Archived</button>
      <button type="button" data-uifa-slot="chip" data-uifa-variant="warn" aria-pressed="false">Overdue</button>
    </div>
  </form>
  <div class="arena-columns">
    <article class="uifa-card">
      <h3 data-uifa-slot="title">New project</h3>
      <p data-uifa-slot="body">Projects group episodes, assets, and delivery checks in one place.</p>
      <label class="uifa-field">
        <span data-uifa-slot="label">Project name</span>
        <input class="uifa-field-input" type="text" placeholder="Acme Inc">
      </label>
      <div data-uifa-slot="actions">
        <button class="uifa-button" data-uifa-variant="primary">Create project</button>
        <button class="uifa-button" data-uifa-variant="secondary">Cancel</button>
      </div>
    </article>
    <article class="uifa-card">
      <h3 data-uifa-slot="title">Delivery queue</h3>
      <div data-uifa-slot="body" class="arena-rows">
        <div class="uifa-link-row">
          <a data-uifa-slot="title" href="#">Episode 12: Designing for agents</a>
          <span data-uifa-slot="url">acme.example/12</span>
          <div data-uifa-slot="chips"><span data-uifa-slot="chip">podcast</span></div>
          <div data-uifa-slot="actions"><a href="#">Open</a></div>
        </div>
        <div class="uifa-link-row">
          <a data-uifa-slot="title" href="#">Season wrap report</a>
          <span data-uifa-slot="url">acme.example/wrap</span>
          <div data-uifa-slot="chips"><span data-uifa-slot="chip">report</span></div>
          <div data-uifa-slot="actions"><a href="#">Open</a></div>
        </div>
        <p class="arena-badges"><span class="uifa-badge" data-uifa-variant="ok">Open</span> <span class="uifa-badge" data-uifa-variant="warn">Due soon</span> <span class="uifa-badge" data-uifa-variant="muted">Closed</span></p>
      </div>
    </article>
  </div>
  <article class="uifa-card">
    <h3 data-uifa-slot="title">Playback</h3>
    <div class="arena-player-row">
      <div class="uifa-player">
        <button type="button" data-uifa-slot="play" aria-label="Play">▶</button>
        <div data-uifa-slot="meta">
          <span data-uifa-slot="title">Episode 12: Designing for agents</span>
          <span data-uifa-slot="time">12:04 / 35:00</span>
        </div>
        <div data-uifa-slot="progress" role="progressbar" aria-label="Playback position" aria-valuemin="0" aria-valuemax="100" aria-valuenow="35">
          <span data-uifa-slot="progress-fill" style="width: 35%"></span>
        </div>
      </div>
      <div class="uifa-segmented" role="radiogroup" aria-label="Sample range">
        <label class="uifa-segmented-option"><input type="radio" name="sample-range" value="day" checked><span data-uifa-slot="segment">Day</span></label>
        <label class="uifa-segmented-option"><input type="radio" name="sample-range" value="week"><span data-uifa-slot="segment">Week</span></label>
      </div>
      <label class="uifa-toggle">
        <input class="uifa-toggle-input" type="checkbox" role="switch" checked>
        <span data-uifa-slot="label">Autoplay next episode</span>
      </label>
    </div>
  </article>
  <table class="uifa-table" data-sortable>
    <thead>
      <tr>
        <th><input data-uifa-slot="select" type="checkbox" aria-label="Select all rows"></th>
        <th aria-sort="ascending"><button type="button">Name</button></th>
        <th>Status</th>
        <th><button type="button">Updated</button></th>
      </tr>
    </thead>
    <tbody>
      <tr><td><input data-uifa-slot="select" type="checkbox" aria-label="Select Atlas"></td><td>Atlas</td><td><span data-uifa-slot="status">Active</span></td><td>2026-09-21</td></tr>
      <tr><td><input data-uifa-slot="select" type="checkbox" aria-label="Select Beacon"></td><td>Beacon</td><td><span data-uifa-slot="status" data-uifa-variant="warn">Due soon</span></td><td>2026-09-24</td></tr>
      <tr><td><input data-uifa-slot="select" type="checkbox" aria-label="Select Compass"></td><td>Compass</td><td><span data-uifa-slot="status" data-uifa-variant="danger">Expired</span></td><td>2026-09-12</td></tr>
    </tbody>
  </table>
  <div class="arena-controls">
    <p class="arena-status-label">Status roles: ok, warn, danger, scrim</p>
    <button type="button" class="uifa-toast-trigger" data-uifa-slot="sample-toast-open">Show toast</button>
    <button type="button" class="uifa-modal-trigger" data-uifa-slot="sample-modal-open">Delete workspace</button>
  </div>
  <div class="arena-scrim-demo">Content under the scrim</div>
</div>
<div class="uifa-toast-region">
  <div class="uifa-toast" data-uifa-variant="info" data-state="visible" role="status">
    <span data-uifa-slot="message">Sample workspace ready</span>
    <button type="button" data-uifa-slot="close">Dismiss</button>
  </div>
  <div class="uifa-toast" data-uifa-variant="ok" data-state="visible" role="status">
    <span data-uifa-slot="message">Delivery queued</span>
    <button type="button" data-uifa-slot="close">Dismiss</button>
  </div>
  <div class="uifa-toast" data-uifa-variant="warn" data-state="visible" role="status">
    <span data-uifa-slot="message">Storage almost full</span>
    <button type="button" data-uifa-slot="close">Dismiss</button>
  </div>
  <div class="uifa-toast" data-uifa-variant="danger" data-state="visible" role="status">
    <span data-uifa-slot="message">Connection lost</span>
    <button type="button" data-uifa-slot="close">Dismiss</button>
  </div>
</div>
`.trim();

const iframeChrome = `
  *, *::before, *::after { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--uifa-bg);
    color: var(--uifa-text);
    font-family: var(--uifa-font-body);
    font-size: var(--uifa-text-base);
  }
  .arena-sample {
    padding: calc(var(--uifa-space) * 4);
    display: grid;
    gap: calc(var(--uifa-space) * 4);
  }
  .arena-page-head {
    display: grid;
    gap: calc(var(--uifa-space) * 1);
  }
  .arena-page-head h2 {
    margin: 0;
    font-family: var(--uifa-font-display);
    font-size: calc(var(--uifa-text-base) * 1.5);
    font-weight: 600;
    line-height: 1.25;
  }
  .arena-page-head p {
    margin: 0;
    max-width: 60ch;
    color: var(--uifa-text-muted);
  }
  .arena-columns {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: calc(var(--uifa-space) * 4);
  }
  .arena-player-row {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: calc(var(--uifa-space) * 4);
  }
  .arena-player-row .uifa-player { flex: 1 1 320px; }
  .arena-rows { display: grid; gap: calc(var(--uifa-space) * 1); }
  .arena-badges { margin: calc(var(--uifa-space) * 1) 0 0; display: flex; gap: calc(var(--uifa-space) * 2); flex-wrap: wrap; }
  .arena-controls {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: calc(var(--uifa-space) * 3);
  }
  .arena-status-label {
    margin: 0 auto 0 0;
    font-family: var(--uifa-font-display);
    color: var(--uifa-text-muted);
  }
  .arena-scrim-demo {
    position: relative;
    border: 1px solid var(--uifa-border);
    border-radius: var(--uifa-radius-control);
    padding: calc(var(--uifa-space) * 2);
    min-height: calc(var(--uifa-space) * 10);
    display: grid;
    place-items: center;
    color: var(--uifa-text-muted);
  }
  .arena-scrim-demo::after {
    content: "";
    position: absolute;
    inset: 0;
    background: var(--uifa-scrim);
    border-radius: inherit;
  }
  /* The catalog renders in flow: fixed regions would paint over the last item.
     The region sits at body level, so it carries the sample's inline padding. */
  .uifa-toast-region {
    position: static;
    justify-items: start;
    row-gap: calc(var(--uifa-space) * 2);
    padding-inline: calc(var(--uifa-space) * 4);
  }
  /* The kit ships items without external margins, so the demo supplies the
     consumer-style spacing between a composed field and its action row. */
  .arena-sample .uifa-card .uifa-field { margin-bottom: calc(var(--uifa-space) * 3); }
  /* Columned footers need width to show their columns; the catalog shrink-wraps items. */
  .arena-item .uifa-footer { min-width: min(640px, 100%); }
  .arena-item {
    border-top: 1px solid var(--uifa-border);
    padding: calc(var(--uifa-space) * 4);
    display: grid;
    gap: calc(var(--uifa-space) * 3);
    justify-items: start;
  }
  .arena-item h3 {
    margin: 0;
    font-family: var(--uifa-font-display);
    font-size: calc(var(--uifa-text-base) * 0.875);
    font-weight: 600;
    color: var(--uifa-text-muted);
  }
`;

// Theme-scoped arena presentation, not kit artifacts: the glass dialect is
// load-bearing on a colorful backdrop behind its frosted panels, so its page
// paints one. Stops stay deep and semi-transparent so the backdrop's
// luminance band stays near --uifa-bg and the contrast-validated glass pairs
// hold over the glow cores.
const arenaChromeExtras = {
  glass: `
  html[data-theme="glass"] body {
    background:
      radial-gradient(52% 44% at 12% 8%, oklch(35% 0.16 335 / 0.5), transparent 70%),
      radial-gradient(48% 42% at 88% 12%, oklch(34% 0.13 250 / 0.45), transparent 70%),
      radial-gradient(60% 50% at 50% 100%, oklch(34% 0.12 175 / 0.4), transparent 72%),
      var(--uifa-bg);
    background-attachment: fixed;
  }
`,
};

function themeDocument(theme) {
  const itemsHtml = itemBlocks
    .map(({ name, body }) => `<section class="arena-item"><h3>${name}</h3>\n${body}\n</section>`)
    .join("\n");
  const chromeExtra = arenaChromeExtras[theme.slug] ?? "";
  return `<!doctype html>
<html lang="en" data-theme="${theme.slug}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
${themesLayerStyle(themes)}
</style>
<style>${itemBlocks.map((b) => b.css).join("\n\n")}</style>
<style>${iframeChrome}</style>
<style>${chromeExtra}</style>
</head>
<body>
${sampleUi}
${itemsHtml}
</body>
</html>`;
}

const pages = themes.map((theme) => ({
  slug: theme.slug,
  name: theme.name,
  mood: theme.mood,
  notes: theme.notes,
  html: themeDocument(theme),
}));

const payload = JSON.stringify({ pages }).replace(/<\//g, "<\\/");

const arena = `<!doctype html>
<!-- GENERATED by scripts/build-arena.mjs - uiforagents ${version} - do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>uiforagents arena</title>
<style>
  body { margin: 0; padding: 24px; font-family: system-ui, sans-serif; background: #f4f2ee; color: #26221e; }
  header { max-width: 1100px; margin: 0 auto 20px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  p { margin: 0; color: #6b645c; font-size: 13px; }
  main { max-width: 1100px; margin: 0 auto; display: grid; gap: 28px; }
  section h2 { font-size: 13px; font-weight: 600; margin: 0 0 8px; }
  iframe { width: 100%; border: 1px solid #d4d0c9; border-radius: 10px; background: #fff; box-shadow: 0 1px 2px rgb(0 0 0 / 0.05), 0 12px 32px rgb(0 0 0 / 0.06); }
</style>
</head>
<body>
<header>
  <h1>uiforagents arena</h1>
  <p>Every item and the sample UI, rendered across the example themes via tokens and dialect layers. Generated by scripts/build-arena.mjs.</p>
</header>
<main id="frames"></main>
<script type="application/json" id="arena-payload">${payload}</script>
<script>
  const payload = JSON.parse(document.getElementById("arena-payload").textContent);
  const main = document.getElementById("frames");
  for (const page of payload.pages) {
    const section = document.createElement("section");
    const h2 = document.createElement("h2");
    h2.textContent = page.name + " · " + page.slug + " · " + page.mood;
    const frame = document.createElement("iframe");
    frame.title = page.name + " theme";
    frame.addEventListener("load", () => {
      try { frame.style.height = frame.contentDocument.documentElement.scrollHeight + "px"; } catch (err) {}
    });
    frame.srcdoc = page.html;
    section.append(h2, frame);
    main.append(section);
  }
</script>
</body>
</html>
`;
mkdirSync(join(ROOT, "docs"), { recursive: true });
writeFileSync(join(ROOT, "docs", "arena.html"), arena);

console.log(`build-arena: docs/arena.html and themes/tokens.css generated (${themes.length} themes, ${items.length} items)`);
