// Per-project flow CLI: `add | tokens | scaffold`, driven by the project's
// uiforagents.json. Copies the configured item subset into the project,
// writes the project's tokens.css from the chosen direction, and scaffolds
// docs/design-system.md. The adherence linter lives in validation/check.mjs.
//
// Usage:
//   node scripts/uifa.mjs add | tokens | scaffold [--config <path>]
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { findConfig, loadConfig, resolveInRoot } from "./lib/config.mjs";

const USAGE = "usage: node scripts/uifa.mjs add | tokens | scaffold [--config <path>]";

const args = process.argv.slice(2);
const configFlagIndex = args.indexOf("--config");
const configFlag = configFlagIndex === -1 ? null : args[configFlagIndex + 1];
const command = args.filter((arg, index) => arg !== "--config" && index !== configFlagIndex && (configFlagIndex === -1 || index !== configFlagIndex + 1))[0];
if (!command || !["add", "tokens", "scaffold"].includes(command)) {
  console.error(USAGE);
  process.exit(1);
}

const configPath = configFlag ? resolve(process.cwd(), configFlag) : findConfig(process.cwd());
if (!configPath) {
  console.error(`uifa: no uiforagents.json found from the working directory upward; pass --config`);
  process.exit(1);
}
const config = loadConfig(configPath);
const kitRoot = resolve(config.root, config.kit);
for (const required of ["items", "registry.json", "themes", "scripts"]) {
  if (!statSync(join(kitRoot, required), { throwIfNoEntry: false })) {
    console.error(`uifa: this is not a uiforagents kit checkout: ${kitRoot}`);
    process.exit(1);
  }
}

const relFromRoot = (path) => relative(config.root, path);
const writeFileManaged = (path, content) => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
};

function loadManifest(name) {
  const manifestPath = join(kitRoot, "items", name, "item.json");
  try {
    return JSON.parse(readFileSync(manifestPath, "utf8"));
  } catch {
    throw new Error(`uifa: config item "${name}" is not in the kit (missing ${manifestPath})`);
  }
}

async function loadDirection() {
  const source = config.directionsFile
    ? resolveInRoot(config.root, config.directionsFile, "directionsFile")
    : join(kitRoot, "themes", "directions.mjs");
  if (!statSync(source, { throwIfNoEntry: false })) {
    throw new Error(`uifa: directions module not found: ${source}`);
  }
  const { directions } = await import(pathToFileURL(source).href);
  const direction = directions.find((d) => d.slug === config.direction);
  if (!direction) {
    throw new Error(`uifa: direction "${config.direction}" not found in ${relFromRoot(source)}`);
  }
  return { direction, source };
}

function tokensCssPath() {
  return resolveInRoot(config.root, config.dest.tokensCss, "dest.tokensCss");
}

function add() {
  const itemsDir = resolveInRoot(config.root, config.dest.itemsDir, "dest.itemsDir");
  const tokensPath = tokensCssPath();
  for (const name of config.items) {
    const manifest = loadManifest(name);
    const destDir = join(itemsDir, name);
    // Examples ship linking the kit's tokens.css two levels up; point them at
    // the project's own tokens.css so the copies render in the chosen direction.
    const tokensHref = relative(destDir, tokensPath).split("\\").join("/");
    for (const file of manifest.files) {
      let content = readFileSync(join(kitRoot, "items", name, file.path), "utf8");
      if (file.type === "kit:example") {
        content = content.replace(/href="[^"]*themes\/tokens\.css"/, `href="${tokensHref}"`);
      }
      writeFileManaged(join(destDir, basename(file.path)), content);
    }
    console.log(`add: ${name} -> ${relFromRoot(destDir)} (${manifest.files.length} files)`);
  }
}

async function tokens() {
  const { direction, source } = await loadDirection();
  const body = Object.entries(direction.tokens)
    .map(([token, value]) => `  ${token}: ${value};`)
    .join("\n");
  const origin = config.directionsFile ?? "the kit's themes/directions.mjs";
  writeFileManaged(tokensCssPath(), `/* GENERATED by uiforagents uifa tokens from ${origin} - do not edit. */\n\n:root {\n${body}\n}\n`);
  console.log(`tokens: ${direction.name} (${direction.slug}) from ${origin} -> ${config.dest.tokensCss}`);
}

async function scaffold() {
  const { direction } = await loadDirection();
  const tokensPath = tokensCssPath();
  if (!existsSync(tokensPath)) {
    throw new Error(`uifa: ${config.dest.tokensCss} not found; run "uifa tokens" first`);
  }
  const tokensCss = readFileSync(tokensPath, "utf8");
  const tokenRows = [...tokensCss.matchAll(/(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);/g)]
    .map((match) => `| \`${match[1]}\` | \`${match[2]}\` |`)
    .join("\n");
  const scheme = tokensCss.match(/color-scheme\s*:\s*([^;]+);/);
  const componentRows = config.items
    .map((name) => {
      const manifest = loadManifest(name);
      return `| ${manifest.title} | ${manifest.description} |`;
    })
    .join("\n");
  const kitBin = (script) => `node ${kitRoot}/${script}`;
  const docs = `# Design system

Direction: **${direction.name}** (\`${direction.slug}\`) - ${direction.mood}. ${direction.notes}

Generated by [uiforagents](https://github.com/peteretelej/uiforagents); the
committed \`${config.dest.tokensCss}\` is the source of truth. Regenerate with
the flow commands and commit the output.

## Tokens

Declared in \`${config.dest.tokensCss}\`${scheme ? ` (color-scheme: ${scheme[1]})` : ""}:

| Token | Value |
| --- | --- |
${tokenRows}

## Components

Copied subset, managed by \`uifa add\` under \`${config.dest.itemsDir}/\`:

| Component | Description |
| --- | --- |
${componentRows}

## Adherence

\`check\` lints the configured HTML/CSS against the registry and reports -
never auto-corrects - three violation classes: raw hex colors, invalid or
missing \`data-variant\`, and tokens outside the copied items' \`cssVars\` and
this project's \`${config.dest.tokensCss}\`. Lint scope: ${config.lint.map((globPattern) => `\`${globPattern}\``).join(", ")}.

## Flow

Config: \`uiforagents.json\`.

\`\`\`sh
${kitBin("scripts/uifa.mjs tokens")}
${kitBin("scripts/uifa.mjs add")}
${kitBin("scripts/uifa.mjs scaffold")}
${kitBin("validation/check.mjs")}
\`\`\`
`;
  writeFileManaged(resolveInRoot(config.root, config.dest.docs, "dest.docs"), docs);
  console.log(`scaffold: ${config.dest.docs} from ${config.dest.tokensCss} + config`);
}

try {
  if (command === "add") add();
  else if (command === "tokens") await tokens();
  else if (command === "scaffold") await scaffold();
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
