<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/badge/badge.html. Tokens and the item stylesheet apply
     unchanged; Vue is the consumer's dependency. -->

<script setup>
defineProps({
  variant: { type: String, default: "accent" },
});

</script>

<template>
  <span class="uifa-badge" :data-uifa-variant="variant">
    <slot />
  </span>
</template>
