<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/button/button.html. Tokens and the item stylesheet apply
     unchanged; Vue is the consumer's dependency. -->

<script setup>
defineProps({
  variant: { type: String, default: "primary" },
  disabled: { type: Boolean, default: false },
});

</script>

<template>
  <button class="uifa-button" :data-uifa-variant="variant" :disabled="disabled">
    <slot />
  </button>
</template>
