<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/card/card.html. Tokens and the item stylesheet apply
     unchanged; Vue is the consumer's dependency. -->

<template>
  <article class="uifa-card">
    <h3 data-uifa-slot="title"><slot name="title" /></h3>
    <p data-uifa-slot="body"><slot name="body" /></p>
    <div data-uifa-slot="actions"><slot name="actions" /></div>
  </article>
</template>
