<!-- GENERATED by scripts/generate-adapters.mjs - uiforagents 0.2.0 - do not edit. -->
<!-- Vanilla twin: items/form-field/form-field.html. Tokens and the item stylesheet apply
     unchanged; Vue is the consumer's dependency. -->

<script setup>
import { useAttrs } from "vue";

defineOptions({ inheritAttrs: false });

defineProps({
  variant: { type: String, default: "text" },
  disabled: { type: Boolean, default: false },
});

const attrs = useAttrs();
</script>

<template>
  <label class="uifa-field">
    <span data-uifa-slot="label"><slot name="label" /></span>
    <textarea v-if="variant === 'textarea'" class="uifa-field-input" data-uifa-variant="textarea" :rows="4" :disabled="disabled" v-bind="attrs"></textarea>
    <input v-else class="uifa-field-input" type="text" :disabled="disabled" v-bind="attrs" />
  </label>
</template>
